# Generated by Django 5.1.2 on 2024-10-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="link_video",
            field=models.CharField(
                blank=True,
                help_text="Укажите ссылку на видео",
                max_length=100,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
